# Generated by Django 5.1 on 2024-08-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_delete_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
